version: '3'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    # volumes:
    #   - ./data/mongodb:/data/db
  app:
    restart: always
    build: .
    environment:
      NODE_ENV: development # or production
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - ${SERVER_PORT}:5000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
      - mongo
    links:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: 
      'redis-server'