version: '3'
services:
  # nginx:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   links:
  #     - app
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      AUTH: 'yes'
      # MONGODB_ADMIN_USER: root
      # MONGODB_ADMIN_PASS: root
      MONGODB_APPLICATION_DATABASE: zhihu
      MONGODB_APPLICATION_USER: restapiuser
      MONGODB_APPLICATION_PASS: r3sT4pIp4ssw0rd
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /var/log/mongodb.log
      MONGO_LOG_LEVEL: 2
    volumes:
      - ./data/mongodb:/data/db
      - ./mongodb_run.sh:/mongodb_run.sh
      - ./set_mongodb_password.sh:/set_mongodb_password.sh
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     chmod +x /mongodb_run.sh
    #     chmod +x /set_mongodb_password.sh
    #     ./mongodb_run.sh
  app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      NODE_ENV: development # or production
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - ${SERVER_PORT}:5000
    volumes:
      - ./:/app
      - /app/node_modules
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 &&
            /usr/wait-for-it.sh --timeout=0 rabbitmq:5672 && npm run dev"
    links:
      - mysql
      - mongo
      - redis
      - rabbitmq
  rabbitmq: 
    image: rabbitmq:management
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_COOKIE: cluster_cookie
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
  redis:
    image: redis:latest
    command: 
      'redis-server'
    ports:
      - 6379:6379