version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
  app:
    container_name: zhihu-app
    restart: always
    build: .
    environment:
      NODE_ENV: development # production
    ports:
      - '5000:5000'
    volumes:
      ['./:/usr/src/app']
    links:
      - redis
      - mongo
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    command: 
      'redis-server'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
networks:
  redis:
    driver: bridge