version: '3'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mongo:
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
  app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      NODE_ENV: development # or production
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - ${SERVER_PORT}:5000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 && 
            /usr/wait-for-it.sh --timeout=0 rabbitmq:5672 && npm run start"
    links:
      - mysql
      - mongo
      - redis
      - rabbitmq
  rabbitmq: 
    image: rabbitmq:management
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_COOKIE: cluster_cookie
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
  redis:
    image: redis:latest
    command: 
      'redis-server'
    ports:
      - 6379:6379