version: '3'
services:
  app:
    container_name: zhihu-app
    restart: always
    build: .
    ports:
      - '80:3000'
    volumes:
      ['./:/usr/src/app']
    links:
      - redis
      - mongo
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    command: 
      'redis-server'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
networks:
  redis:
    driver: bridge