const express = require('express')
const router = express.Router()
const cloudinary = require('cloudinary').v2;
const File = require('../models/file')

router.route('/upload')
  .post((req, res) => {
    if (!req.files || Object.keys(req.files).length === 0) {
      return res.status(400).send('No files were uploaded.');
    }
    const { type } = req.query
    console.log(type)
    if (type === 'image') {
      const { data, name } = req.files.images;
      const { tags, width, height } = req.query
      cloudinary.uploader.upload_stream({
        resource_type: 'image',
        tags: ['tmp'],
        width,
        height,
      }, async (err, image) => {
        console.log(image)
        console.log("** File Upload");
        if (err) {
          res.status(200).json({ success: false, msg: err });
          return;
        }
        console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
        console.log("* " + image.public_id);
        console.log("* " + image.url);

        // store image data
        const newFile = new File({
          name,
          type: image.resource_type,
          format: image.format,
          size: image.bytes,
          publicId: image.public_id,
          url: image.url
        })
        const fileCreated = await newFile.save()
        res.status(200).json({ data: fileCreated })
      }).end(data);
    }
  })

module.exports = router