const express = require('express')
const router = express.Router()
const cloudinary = require('cloudinary').v2;

router.route('/upload')
  .post((req, res) => {
    if (!req.files || Object.keys(req.files).length === 0) {
      return res.status(400).send('No files were uploaded.');
    }
    const { type } = req.query
    console.log(type)
    if (type === 'image') {
      const { data } = req.files.images;
      const { tags, width, height } = req.query
      cloudinary.uploader.upload_stream({
        resource_type: 'image',
        tags: tags.split(','),
        width,
        height,
      }, (err, image) => {
        console.log(image)
        console.log("** File Upload");
        if (err) {
          res.status(200).json({ success: false, msg: err });
          return;
        }
        console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
        console.log("* " + image.public_id);
        console.log("* " + image.url);
        res.status(200).json({ data: image })
      }).end(data);
    }
  })

module.exports = router