const cloudinary = require('cloudinary').v2;
const File = require('../models/file')

class UploadController {
  constructor() {
  }

  static async uploadImages(files, options) {
    const { data, name } = files.images;
    const { width, height } = options
    cloudinary.uploader.upload_stream({
      resource_type: 'image',
      tags: ['tmp'],
      width,
      height,
    }, async (err, image) => {
      console.log(image)
      console.log("** File Upload");

      if (err) {
        return { status: 0, msg: err };
      }

      console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
      console.log("* " + image.public_id);
      console.log("* " + image.url);

      // store image data
      const newFile = new File({
        name,
        type: image.resource_type,
        format: image.format,
        size: image.bytes,
        publicId: image.public_id,
        url: image.url
      })
      const fileCreated = await newFile.save()
      return { status: 1, data: fileCreated };
    }).end(data);
  }
}

module.exports = UploadController